# -*- coding: utf-8 -*-
"""
Django settings for stickers project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'q#tunvieo)z)nr8-^sxbc69#b2pwl-9rgz8gf*+)8@^0b+f3*b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

TEMPLATE_DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tasks',
    'registration',
    'customuseradmin',
    'social_auth',
)

AUTHENTICATION_BACKENDS = (
    'social_auth.backends.google.GoogleOAuth2Backend',
    'social_auth.backends.facebook.FacebookBackend',
    'stickers.email-auth.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
)



TEMPLATE_CONTEXT_PROCESSORS = (
    'django.contrib.auth.context_processors.auth',
    'django.core.context_processors.request',
    'social_auth.context_processors.social_auth_by_name_backends',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

GOOGLE_OAUTH2_CLIENT_ID = '967560025228-83gnsnpcv5r91ts427vanpipifeisccr.apps.googleusercontent.com'
GOOGLE_OAUTH2_CLIENT_SECRET = '5PMndZPRNF5bjmYVMeu4x180'


FACEBOOK_APP_ID = '937590722980451'
FACEBOOK_API_SECRET = '27188c1a90b35dce7fa0f8e059aa9487'

ROOT_URLCONF = 'stickers.urls'


WSGI_APPLICATION = 'stickers.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

TEMPLATE_DIRS = [os.path.join(BASE_DIR, 'templates')]

STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

#Отправка писем для подтверждения регистрации на сайте
ACCOUNT_ACTIVATION_DAYS = 3 # кол-во дней для хранения кода активации

FACEBOOK_EXTENDED_PERMISSIONS = ['email']
LOGIN_REDIRECT_URL = '/accounts/profile/'
SESSION_SERIALIZER='django.contrib.sessions.serializers.PickleSerializer'

#Send email with service send grid
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_HOST_USER = 'NikolayB'
EMAIL_HOST_PASSWORD = 'acmilan86'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
